#ifndef SERVER_H
#define SERVER_H
#include <vector>
#include <stdint.h>

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    // buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
};

void fd_set_nb(int fd);

// application callbacks
Conn *handle_accept(int fd); // used when the listening socket is ready
void handle_read(Conn *conn); // used when the socket is readable
void handle_write(Conn *); // used when the socket is writeable
#endif