#ifndef SERVER_H
#define SERVER_H
#include <string>
#include <vector>
#include <cstdint>

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    // buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
};

void fd_set_nb(int fd);

// application callbacks
Conn *handle_accept(int fd); // used when the listening socket is ready
void handle_read(Conn *conn); // used when the socket is readable
void handle_write(Conn *); // used when the socket is writeable

struct Response {
    uint32_t status = 0;
    std::vector<uint8_t> data;
};

enum {
    RES_OK = 0,
    RES_ERR = 1,
    RES_NX = 2
};

int32_t parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out);
bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out);
bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out);

void do_request(std::vector<std::string> &cmd, Response &out);
void make_response(const Response &resp, std::vector<uint8_t> &out);
#endif